"""add user_id to campaigns leads calls bookings

Revision ID: 570159e110b4
Revises: 470f2e081571
Create Date: 2026-08-02 00:00:01.075627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570159e110b4'
down_revision: Union[str, Sequence[str], None] = '470f2e081571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('calls', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_calls_user_id'), 'calls', ['user_id'], unique=False)
    op.create_foreign_key(None, 'calls', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('campaigns', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.create_foreign_key(None, 'campaigns', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('leads', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_leads_user_id'), 'leads', ['user_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_user_id'), table_name='leads')
    op.drop_column('leads', 'user_id')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    op.drop_column('campaigns', 'user_id')
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.drop_index(op.f('ix_calls_user_id'), table_name='calls')
    op.drop_column('calls', 'user_id')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_column('bookings', 'user_id')
    # ### end Alembic commands ###
