"""Cross-service constants: Redis key templates, call status enums, etc."""

CALL_STATE_KEY = "call:{call_id}:state"
CALL_TRANSCRIPT_BUFFER_KEY = "call:{call_id}:transcript_buffer"
CALL_SENTIMENT_KEY = "call:{call_id}:sentiment"
DIALER_QUEUE_KEY = "dialer:queue:{campaign_id}"
DIALER_PROCESSING_KEY = "dialer:processing:{campaign_id}"
GHOST_MODE_NOTE_KEY = "ghost_mode:{room_name}:note"
CALL_PITCH_VARIANT_KEY = "call:{room_name}:pitch_variant"
BRIEFING_SENT_KEY = "briefing:sent:{date}"
CRM_WEBHOOK_FAILED_KEY = "crm:webhook:failed"
